### ISSUE TITLE
Only unban IP if attack is gone/has ended

### ISSUE THREAD

**Issue by Phinitris** [FastVPSEestiOu/fastnetmon#139]
Hey,
we should only clean up the banlist for an ip address when the attack has ended.

**Comment by pavel-odintsov** [comment]
Hello!

You suggest additional check for traffic speed on banned IP before unblock, right?

**Comment by Phinitris** [comment]
Hello Pavel,
that's right.
If prefered you can also add an option if an additional check should be done in /etc/fastnetmon.conf

**Comment by pavel-odintsov** [comment]
Nice idea! I will do this feature!

**Comment by Phinitris** [comment]
That's cool. Any ETA?

**Comment by pavel-odintsov** [comment]
I added few related commits and will add this feature soon. Do you have time for testing?

**Comment by Phinitris** [comment]
Sure.
Let me know, if it's ready for testing.

**Comment by pavel-odintsov** [comment]
It's very important issue! It should be implemented ASAP.

**Comment by s4m4n** [comment]
Pavel,

when attacked IP address is blackholed, we cannot observe the traffic via Flow data as far as packets won't hit the router. it's vital to have it auto-withdraw the blackhole when the attack is gone. we might setup a cronjob that runs every 15 minutes or whatever and flush blacklist and withdraw the blackhole. in case that the attack is not stopped, Fastnetmon will detect and ban it again.

It would be a simple bash script to so the thing.

Can you advice how do you maintain the ban list ? I'd need to know in order to remove the IP from banlist and withdraw the blackhole via ExaBGP API.

echo "withdraw route 1.2.3.4/32" > /var/run/exabgp.cmd

**Comment by pavel-odintsov** [comment]
Hello, Saman!

We already have option to unban IP addresses. You could specify timeout for unblock with ban_time = 1900 and when 1900 seconds after attack detection lasted we will withdraw announce with ExaBGP.

Do you still want some way to manually unblock blocked IP's?

**Comment by s4m4n** [comment]
Hello, Great! Thanks

**Comment by pavel-odintsov** [comment]
Default action for unban changed. We check traffic to blocked IP and this traffic still exceed threshold, we do not unblock it!
